### ISSUE TITLE
Awesome I got it loading, but where are total stats? 

### ISSUE THREAD

**Issue by minicoz** [Nachtalb/more-upload-stats#6]
I like it! It works for me, but it only displays the current stats. Is there a way to get lifetime stats? 

Everytime I refresh my nicotine+ my current stats go back to zero but the server stats stay

**Comment by Nachtalb** [comment]
I haven't used nicotine+ in a while, I'll try to look into it in a timely manner (by earliest start of next week)

**Comment by Nachtalb** [comment]
as mentioned in the readme: 

> ⚠ No data previous to enabling this plugin will be available.

1. The stats you get from the server are not the same stats I track with this plugin: 
![image](https://github.com/user-attachments/assets/f1ba5ba5-91fb-4050-81b7-64f2e03058e5)
	These are the server stats. You don't see which file you uploaded to whom for how many times and how large the file is etc. 
	
2. The stats that N+ collets itself are again not the same stats I collect with this plugin - that's the whole reason as to why this plugin even exists.

**Comment by minicoz** [comment]
understood thanks

**Comment by Nachtalb** [comment]
run /up-open-page in any chat to open the stats page.

**Comment by Nachtalb** [comment]
I just realised that `/up-open-page` doesn't work on my pc, presumably due to changes on Nicotine+'s Plugin implementation side. The more general command still works tho `/up-open`. 

`/up-open` will however open both the webpage and the playlist of most downloaded music files at the same time. So you'll have to close that playlist if you don't wanna listen to it 😄 

As said in  the quick updated I uploaded a few mins ago: https://github.com/Nachtalb/more-upload-stats/releases/tag/v2.2.1 - I will be upgrading this package to my new plugin code library. So it'll take a bit until I have everything done. Until then I won't make more bugfixes. https://nicotine-plugin-core-npc.readthedocs.io/stable/
